// Mock data for the dashboard UI. Replace with Prisma queries once the database is in place.

export const mockUser = {
  id: "user_1",
  name: "Jane Doe",
  email: "demo@devstash.com",
  image: null as string | null,
  isPro: false,
};

export const mockItemTypes = [
  { id: "type_snippet", name: "snippet", slug: "snippets", icon: "Code", color: "#3b82f6", isSystem: true, itemCount: 24 },
  { id: "type_prompt", name: "prompt", slug: "prompts", icon: "Sparkles", color: "#8b5cf6", isSystem: true, itemCount: 18 },
  { id: "type_command", name: "command", slug: "commands", icon: "Terminal", color: "#f97316", isSystem: true, itemCount: 15 },
  { id: "type_note", name: "note", slug: "notes", icon: "StickyNote", color: "#fde047", isSystem: true, itemCount: 12 },
  { id: "type_file", name: "file", slug: "files", icon: "File", color: "#6b7280", isSystem: true, itemCount: 5 },
  { id: "type_image", name: "image", slug: "images", icon: "Image", color: "#ec4899", isSystem: true, itemCount: 3 },
  { id: "type_link", name: "link", slug: "links", icon: "Link", color: "#10b981", isSystem: true, itemCount: 8 },
];

// typeIds: types contained in the collection, most common first (the first one drives the card color)
export const mockCollections = [
  {
    id: "col_react_patterns",
    name: "React Patterns",
    description: "Common React patterns and hooks",
    isFavorite: true,
    itemCount: 12,
    typeIds: ["type_snippet", "type_note", "type_link"],
  },
  {
    id: "col_python_snippets",
    name: "Python Snippets",
    description: "Useful Python code snippets",
    isFavorite: false,
    itemCount: 8,
    typeIds: ["type_snippet", "type_note"],
  },
  {
    id: "col_context_files",
    name: "Context Files",
    description: "AI context files for projects",
    isFavorite: true,
    itemCount: 5,
    typeIds: ["type_file", "type_note"],
  },
  {
    id: "col_interview_prep",
    name: "Interview Prep",
    description: "Technical interview preparation",
    isFavorite: false,
    itemCount: 24,
    typeIds: ["type_note", "type_snippet", "type_link", "type_prompt"],
  },
  {
    id: "col_git_commands",
    name: "Git Commands",
    description: "Frequently used git commands",
    isFavorite: true,
    itemCount: 15,
    typeIds: ["type_command", "type_note"],
  },
  {
    id: "col_ai_prompts",
    name: "AI Prompts",
    description: "Curated AI prompts for coding",
    isFavorite: false,
    itemCount: 18,
    typeIds: ["type_prompt", "type_snippet", "type_note"],
  },
];

export const mockItems = [
  {
    id: "item_1",
    title: "useAuth Hook",
    description: "Custom authentication hook for React applications",
    contentType: "TEXT",
    content:
      "export function useAuth() {\n  const { data: session, status } = useSession();\n  return { user: session?.user, isLoading: status === \"loading\" };\n}",
    language: "typescript",
    url: null as string | null,
    typeId: "type_snippet",
    collectionIds: ["col_react_patterns"],
    tags: ["react", "auth", "hooks"],
    isFavorite: true,
    isPinned: true,
    createdAt: "2026-01-15T10:00:00Z",
    lastUsedAt: "2026-01-15T10:00:00Z",
  },
  {
    id: "item_2",
    title: "API Error Handling Pattern",
    description: "Fetch wrapper with exponential backoff retry logic",
    contentType: "TEXT",
    content:
      "async function fetchWithRetry(url: string, retries = 3) {\n  for (let i = 0; i < retries; i++) {\n    try {\n      return await fetch(url);\n    } catch {\n      await new Promise((r) => setTimeout(r, 2 ** i * 1000));\n    }\n  }\n  throw new Error(\"Request failed\");\n}",
    language: "typescript",
    url: null as string | null,
    typeId: "type_snippet",
    collectionIds: ["col_react_patterns", "col_interview_prep"],
    tags: ["api", "fetch", "error-handling"],
    isFavorite: false,
    isPinned: true,
    createdAt: "2026-01-12T10:00:00Z",
    lastUsedAt: "2026-01-14T10:00:00Z",
  },
  {
    id: "item_3",
    title: "Code Review Prompt",
    description: "Thorough code review focused on bugs and readability",
    contentType: "TEXT",
    content:
      "Review the following code. Point out bugs, security issues, and readability problems. Suggest concrete fixes.",
    language: null as string | null,
    url: null as string | null,
    typeId: "type_prompt",
    collectionIds: ["col_ai_prompts"],
    tags: ["review", "ai"],
    isFavorite: true,
    isPinned: false,
    createdAt: "2026-01-10T10:00:00Z",
    lastUsedAt: "2026-01-13T10:00:00Z",
  },
  {
    id: "item_4",
    title: "Undo Last Commit",
    description: "Undo the last commit but keep the changes staged",
    contentType: "TEXT",
    content: "git reset --soft HEAD~1",
    language: "bash",
    url: null as string | null,
    typeId: "type_command",
    collectionIds: ["col_git_commands"],
    tags: ["git"],
    isFavorite: false,
    isPinned: false,
    createdAt: "2026-01-09T10:00:00Z",
    lastUsedAt: "2026-01-12T10:00:00Z",
  },
  {
    id: "item_5",
    title: "Docker Compose Up",
    description: "Rebuild and start all services in the background",
    contentType: "TEXT",
    content: "docker compose up -d --build",
    language: "bash",
    url: null as string | null,
    typeId: "type_command",
    collectionIds: [],
    tags: ["docker"],
    isFavorite: false,
    isPinned: false,
    createdAt: "2026-01-08T10:00:00Z",
    lastUsedAt: "2026-01-11T10:00:00Z",
  },
  {
    id: "item_6",
    title: "Big O Cheat Sheet",
    description: "Time and space complexity of common algorithms",
    contentType: "TEXT",
    content: "## Sorting\n\n- Merge sort: O(n log n)\n- Quick sort: O(n log n) average, O(n²) worst",
    language: null as string | null,
    url: null as string | null,
    typeId: "type_note",
    collectionIds: ["col_interview_prep"],
    tags: ["algorithms", "interview"],
    isFavorite: false,
    isPinned: false,
    createdAt: "2026-01-07T10:00:00Z",
    lastUsedAt: "2026-01-10T10:00:00Z",
  },
  {
    id: "item_7",
    title: "React Docs",
    description: "Official React documentation",
    contentType: "URL",
    content: null as string | null,
    language: null as string | null,
    url: "https://react.dev",
    typeId: "type_link",
    collectionIds: ["col_react_patterns"],
    tags: ["react", "docs"],
    isFavorite: false,
    isPinned: false,
    createdAt: "2026-01-05T10:00:00Z",
    lastUsedAt: "2026-01-09T10:00:00Z",
  },
  {
    id: "item_8",
    title: "List Comprehension Examples",
    description: "Common Python list comprehension patterns",
    contentType: "TEXT",
    content: "squares = [x**2 for x in range(10)]\nevens = [x for x in range(20) if x % 2 == 0]",
    language: "python",
    url: null as string | null,
    typeId: "type_snippet",
    collectionIds: ["col_python_snippets"],
    tags: ["python"],
    isFavorite: false,
    isPinned: false,
    createdAt: "2026-01-03T10:00:00Z",
    lastUsedAt: "2026-01-08T10:00:00Z",
  },
];
